### PR TITLE
add mx: *.mx.microsoft to MTA-STS Policy Script

### PR DESCRIPTION
**Pull request by BohrenAn**
Added the *.mx.microsoft to support also DANE Domains

### CODE REVIEW

**Comment by BohrenAn** [comment]
Turns out that adding  *.mx.microsoft to MTA-STS Policy does not work.

{
	"organization-name": "Google Inc.",
	"date-range": {
		"start-datetime": "2024-08-02T00:00:00Z",
		"end-datetime": "2024-08-02T23:59:59Z"
	},
	"contact-info": "smtp-tls-reporting@google.com",
	"report-id": "2024-08-02T00:00:00Z_icewolf.li",
	"policies": [
		{
			"policy": {
				"policy-type": "sts",
				"policy-string": [
					"version: STSv1",
					"mode: enforce",
					"mx: *.mail.protection.outlook.com",
					"mx: *.mx.microsoft",
					"mx: mail.icewolf.ch",
					"max_age: 604800"
				],
				"policy-domain": "icewolf.li",
				"mx-host": [
					"*.mail.protection.outlook.com",
					"*.mx.microsoft",
					"mail.icewolf.ch"
				]
			},
			"summary": {
				"total-successful-session-count": 0,
				"total-failure-session-count": 10
			},
			"failure-details": [
				{
					"result-type": "validation-failure",
					"sending-mta-ip": "",
					"receiving-ip": "52.101.185.13",
					"receiving-mx-hostname": "icewolf-li.h-v1.mx.microsoft",
					"failed-session-count": 4
				},
				{
					"result-type": "validation-failure",
					"sending-mta-ip": "",
					"receiving-ip": "52.101.185.12",
					"receiving-mx-hostname": "icewolf-li.h-v1.mx.microsoft",
					"failed-session-count": 3
				},
				{
					"result-type": "validation-failure",
					"sending-mta-ip": "",
					"receiving-ip": "52.101.185.14",
					"receiving-mx-hostname": "icewolf-li.h-v1.mx.microsoft",
					"failed-session-count": 5
				}
			]
		}
	]
}

**Comment by BohrenAn** [comment]
You need to add the Subdomain too. As documented here:
https://techcommunity.microsoft.com/t5/exchange-team-blog/implementing-inbound-smtp-dane-with-dnssec-for-exchange-online/ba-p/3939694 

{
	"organization-name": "Google Inc.",
	"date-range": {
		"start-datetime": "2024-08-03T00:00:00Z",
		"end-datetime": "2024-08-03T23:59:59Z"
	},
	"contact-info": "smtp-tls-reporting@google.com",
	"report-id": "2024-08-03T00:00:00Z_icewolf.li",
	"policies": [
		{
			"policy": {
				"policy-type": "sts",
				"policy-string": [
					"version: STSv1",
					"mode: enforce",
					"mx: *.mail.protection.outlook.com",
					"mx: *.h-v1.mx.microsoft",
					"mx: mail.icewolf.ch",
					"max_age: 604800"
				],
				"policy-domain": "icewolf.li",
				"mx-host": [
					"*.mail.protection.outlook.com",
					"*.h-v1.mx.microsoft",
					"mail.icewolf.ch"
				]
			},
			"summary": {
				"total-successful-session-count": 3,
				"total-failure-session-count": 0
			}
		}
	]
}

Possible Solution:
Add a Array Parameter -MXHost
mx: *.h-v1.mx.microsoft
mx: mail.icewolf.ch
The hole string or just the Domain?

Update-PSMTASTSFunctionAppFile -ResourceGroupName 'rg-PSMTASTS' -FunctionAppName 'func-PSMTASTS' -PolicyMode 'Testing' -MXHost "*.h-v1.mx.microsoft"

Kine Regards
Andres

**Comment by jklotzsche-msft** [comment]
Thank you @BohrenAn for the information! I will include this in the next version of PS.MTA-STS

**Comment by jklotzsche-msft** [comment]
changes will be published with new version 1.3.0 shortly

**Pull request closed without merging**
